definitions:
  user.User:
    properties:
      email:
        type: string
      fname:
        type: string
      id:
        type: integer
      lname:
        type: string
      password:
        type: string
      tel:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  user.resetPass:
    properties:
      newpassword:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Post User
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: Login
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: Get all user
  /api/v1/user/create:
    post:
      consumes:
      - application/json
      description: Post User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: Create user
  /api/v1/user/me:
    get:
      consumes:
      - application/json
      description: Get User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: Get user
    put:
      consumes:
      - application/json
      description: Put User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: Update user
  /api/v1/user/resetpassword:
    patch:
      consumes:
      - application/json
      description: Patch resetPass
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.resetPass'
      summary: Reset password
swagger: "2.0"
