definitions:
  user.User:
    properties:
      email:
        type: string
      fname:
        type: string
      id:
        type: integer
      lname:
        type: string
      password:
        type: string
      tel:
        type: string
      username:
        type: string
    required:
    - email
    - fname
    - lname
    - password
    - tel
    - username
    type: object
info:
  contact: {}
paths:
  /api/v1/user:
    get:
      description: Get User
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: Age
        in: query
        name: age
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      summary: Retrieves user based on query
swagger: "2.0"
