definitions:
  user.User:
    properties:
      email:
        type: string
      fname:
        type: string
      id:
        type: integer
      lname:
        type: string
      password:
        type: string
      tel:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      summary: Retrieves user based on query
swagger: "2.0"
